# Generated by Django 4.2.4 on 2023-10-18 13:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_chatlist'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatlist',
            unique_together={('sender', 'receiver')},
        ),
    ]
