# Generated by Django 4.2.4 on 2023-09-09 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('address_line', models.TextField()),
                ('phone', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FirmVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=50)),
                ('owner_pan_card', models.FileField(upload_to='')),
                ('firm_liscense', models.FileField(upload_to='')),
                ('gst_certificate', models.FileField(upload_to='')),
                ('insurance', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='FirmInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_name', models.CharField(max_length=50)),
                ('website', models.CharField(blank=True, max_length=50, null=True)),
                ('about', models.TextField()),
                ('cover_photo', models.ImageField(upload_to='')),
                ('firm_description', models.TextField()),
                ('awards', models.CharField(max_length=100)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professionals.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('verification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professionals.firmverification')),
            ],
        ),
    ]
