# Generated by Django 4.2.4 on 2023-09-17 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0003_remove_firminfo_address_firminfo_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firminfo',
            name='address',
        ),
        migrations.AddField(
            model_name='firminfo',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='professionals.address'),
            preserve_default=False,
        ),
    ]
