# Generated by Django 4.2.4 on 2023-09-18 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0005_alter_firminfo_address_alter_firminfo_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firminfo',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='firminfo',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='coverphoto/'),
        ),
        migrations.AlterField(
            model_name='firminfo',
            name='firm_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='firminfo',
            name='firm_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
