# Generated by Django 4.2.4 on 2023-09-18 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0006_alter_firminfo_about_alter_firminfo_cover_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firminfo',
            name='cover_photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
