# Generated by Django 4.2.4 on 2023-09-18 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0007_alter_firminfo_cover_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firminfo',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='coverphoto/'),
        ),
    ]
