# Generated by Django 4.2.4 on 2023-09-18 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0009_alter_firmverification_firm_liscense_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project_images/')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50)),
                ('year', models.PositiveSmallIntegerField()),
                ('project_description', models.TextField()),
                ('cost', models.PositiveIntegerField()),
                ('project_address', models.TextField()),
                ('images', models.ManyToManyField(blank=True, null=True, to='professionals.projectimages')),
            ],
        ),
    ]
