# Generated by Django 4.2.4 on 2023-09-18 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0010_projectimages_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='firminfo',
            name='project',
            field=models.ManyToManyField(blank=True, null=True, to='professionals.project'),
        ),
    ]
