# Generated by Django 4.2.4 on 2023-10-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0014_remove_project_images_projectimages_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='firminfo',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='firminfo',
            name='project',
            field=models.ManyToManyField(to='professionals.project'),
        ),
    ]
