# Generated by Django 4.2.4 on 2023-10-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0015_firminfo_approved_alter_firminfo_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firminfo',
            name='approved',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=100),
        ),
    ]
