# Generated by Django 4.2.4 on 2023-10-03 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0016_alter_firminfo_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firminfo',
            old_name='approved',
            new_name='status',
        ),
    ]
