# Generated by Django 4.2.4 on 2023-10-08 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeowners', '0005_customuser_cover_photo_customuser_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('address_line', models.TextField()),
                ('phone', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homeowners.useraddress'),
        ),
    ]
