# Generated by Django 4.2.4 on 2023-10-08 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeowners', '0006_useraddress_customuser_user_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_address',
        ),
        migrations.AddField(
            model_name='useraddress',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
