# Generated by Django 4.2.4 on 2023-10-17 10:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homeowners', '0008_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
